An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: expected string or bytes-like object
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1727089250.6419883-349695-173048712874427/AnsiballZ_organization.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1727089250.6419883-349695-173048712874427/AnsiballZ_organization.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1727089250.6419883-349695-173048712874427/AnsiballZ_organization.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.organization', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.organization', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_tower_organization_payload_gnyrgfu8/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/modules/organization.py\", line 217, in <module>\n  File \"/tmp/ansible_tower_organization_payload_gnyrgfu8/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/modules/organization.py\", line 137, in main\n  File \"/tmp/ansible_tower_organization_payload_gnyrgfu8/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 309, in __init__\n  File \"/tmp/ansible_tower_organization_payload_gnyrgfu8/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 122, in __init__\n  File \"/usr/lib/python3.10/re.py\", line 190, in match\n    return _compile(pattern, flags).match(string)\nTypeError: expected string or bytes-like object\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
